[Service]
ExecStopPost=/bin/sh -c 'echo uart0 > /sys/bus/platform/drivers/aspeed-uart-routing/14c31098.uart-routing/io0'
ExecStopPost=/bin/sh -c 'echo io0 > /sys/bus/platform/drivers/aspeed-uart-routing/14c31098.uart-routing/uart0'
