[Service]
ExecStopPost=/bin/sh -c 'echo uart5 > /sys/bus/platform/drivers/aspeed-uart-routing/14c32098.uart-routing/io5'
ExecStopPost=/bin/sh -c 'echo io5 > /sys/bus/platform/drivers/aspeed-uart-routing/14c32098.uart-routing/uart5'
