[Service]
ExecStopPost=/bin/sh -c 'echo uart1 > /sys/bus/platform/drivers/aspeed-uart-routing/1e789098.uart-routing/io1'
ExecStopPost=/bin/sh -c 'echo io1 > /sys/bus/platform/drivers/aspeed-uart-routing/1e789098.uart-routing/uart1'
