FILESEXTRAPATHS:append := ":${THISDIR}/${PN}"
PROVIDES:remove = "virtual/obmc-host-ipmi-hw"
RPROVIDES:${PN}:remove = "virtual-obmc-host-ipmi-hw"
RRECOMMENDS:${PN}:remove = "phosphor-ipmi-host"
SRC_URI:append = " file://0000-sophgo-ssifbridged.patch "